FROM debian:latest 

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    python3-pip \
    python3 \
    python3-dev \
    && apt-get autoremove \
    && apt-get clean
RUN pip3 install -U pymodbus
CMD []
ENTRYPOINT ["/usr/bin/python2.7"]
